[platformio]
default_envs =
  transmitter
  receiver

[common]
platform = espressif32@6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -Wall
  -Wextra
lib_deps =
  sandeepmistry/LoRa@0.8.0
  rweather/Crypto@0.4.0

[env:transmitter]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}
build_src_filter =
  -<*>
  +<transmitter/>
lib_deps =
  ${common.lib_deps}
  mikalhart/TinyGPSPlus@1.1.0

[env:receiver]
platform = ${common.platform}
board = ${common.board}
framework = ${common.framework}
monitor_speed = ${common.monitor_speed}
build_flags = ${common.build_flags}
build_src_filter =
  -<*>
  +<receiver/>
lib_deps = ${common.lib_deps}

[env:native]
platform = native
test_framework = unity
test_filter = test_protocol
test_build_src = no
build_flags =
  -std=gnu++11
  -Wall
  -Wextra
